### ISSUE TITLE
Logger crashes on missing package

### ISSUE THREAD

**Issue by OsirisTerje** [icnocop/AzurePipelines.TestLogger#12]
I added the logger to the test project, and to the dotnet test command prompt in the pipeline yaml like
```
--logger AzurePipelines;Verbose=true;UseDefaultCredentials=true
```
but got an error when running
```
Error while initializing logger: logger://Microsoft/TestPlatform/AzurePiplinesTestLogger/v1, Exception details: Could not load file or assembly 'Semver, Version=2.0.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
The `semver` package is not part of my csproj, but I see it is part of this component, but not listed as a dependency on nuget.prg for this package.

**Comment by icnocop** [comment]
Please try using the latest NuGet package, https://www.nuget.org/packages/AzurePipelines.TestLogger/1.2.1-build-43

Thank you.
